server:
    port: 8081
spring:
    application:
        name: school
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5432/school
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update

