server:
    port: 8081

management:
    tracing:
        sampling:
            probability: 1.0

spring:
    application:
        name: school
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5432/school
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

student:
    url: http://localhost:8222/api/v1/students