eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/students/**
        - id: school
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/schools/**

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: trace
    org.springframework.web: trace
    org.hibernate: trace