management:
    tracing:
        sampling:
            probability: 1.0

spring:
    application:
        name: student
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5432/students
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

